### ISSUE TITLE
Divide PWD code by functions

### ISSUE THREAD

**Issue by mizun524** [mizun524/PWD#4]

**Comment by mizun524** [comment]
```yaml
start_date: 2022/3/30
due_date: 2022/4/30
progress: 0.1
parent: 1
```
